import { wordsFor, type ScreenProps } from '../components/workspace'

/* The claycols app screen: 1 720 x 450 window of the product, at rest on its finished scene; AppScreen adds .play to
   its root to run the story. Its look and story: css/claycols.css, loaded by the page, never imported here.
   Converted from its HTML by scripts/convert-screens.mjs (3 Oct 2026); this file is the screen's source now. */
export function ClaycolsScreen({ workspace = 'agency' }: ScreenProps) {
  const ws = wordsFor(workspace)
  return (
    <div className="il appx-il app-claycols"><div className="appx-fit"><div className="appx" role="img" aria-label="An agency’s Clay table, its UK ecommerce TAM in the SMS popup view with new rows on: Obsession’s 4 columns attach, Gap, Seen, What happened and Proof. The facts land row by row for Tidewren Swim, Halvard &amp; Moss, Fennick Home and Larkbound, the count reaches 296 of 300 brands done, and the facts are back in Clay.">
      <div className="ax-bar">
        <span className="ax-dots" aria-hidden="true"><i /><i /><i /></span>
        <span className="ax-crumb"><b>{ws.org}</b><span>/</span>Missions<span>/</span>Prospect intelligence</span>
        <span className="ax-search"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5"><circle cx="7" cy="7" r="4.25" /><path d="M10.2 10.2 13 13" /></svg>Search or type a task<span className="ax-kbd">⌘K</span></span>
        <span className="ax-team" aria-hidden="true"><span>AM</span><span>JO</span></span>
      </div>
      <div className="ax-body">
        <aside className="ax-side">
          <div className="ax-ws"><i>Y</i>{ws.org}</div>
          <nav className="ax-nav">
            <a role="none"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"><path d="M2.75 7.25 8 3l5.25 4.25V13H2.75Z" /></svg>Home</a>
            <a className="on" role="none"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"><path d="M3 4.5h10M3 8h10M3 11.5h6" /></svg>Missions<em>24</em></a>
            <a role="none"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5"><rect x="2.75" y="2.75" width="4.5" height="4.5" rx="1" /><rect x="8.75" y="2.75" width="4.5" height="4.5" rx="1" /><rect x="2.75" y="8.75" width="4.5" height="4.5" rx="1" /><rect x="8.75" y="8.75" width="4.5" height="4.5" rx="1" /></svg>Recipes</a>
            <a role="none"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"><path d="M2.5 9.5h3l1 2h3l1-2h3M2.5 9.5 4 3.5h8l1.5 6v3.25h-11Z" /></svg>Needs you<span className="ax-badge">3</span></a>
            <a role="none"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"><path d="M4 2.5h8v11l-2-1.25-2 1.25-2-1.25-2 1.25Z" /><path d="M6 6h4M6 8.75h4" strokeLinecap="round" /></svg>Records</a>
          </nav>
          <div className="ax-clients">
            <p className="ax-side-h">{ws.lists}</p>
            <a role="none"><i />Homeware</a><a role="none"><i />Coffee roaster</a><a role="none"><i />Candles</a><a role="none"><i />Outdoor gear</a><a role="none"><i />Dental group</a>
          </div>
          <div className="ax-side-f"><svg className="sig st-working moving" viewBox="2 2 96 96" aria-hidden="true"><g className="sig-rot"><path className="sig-ring" d="M88.57 39.402A40 40 0 1 1 60.598 11.43V21.668A29.319 30.387 0 1 0 77.478 39.402Z" /><path className="sig-gap" d="M60.598 11.43A40 40 0 0 1 88.57 39.402H77.478A29.319 30.387 0 0 0 60.598 21.668Z" /><g className="sig-orb"><path className="sig-sq" d="M65.404 16.011h18.585v18.585h-18.585Z" /></g></g></svg><span><b>37</b> agents working</span></div>
        </aside>
        <div className="ax-main">
          <header className="ccl-h ax-fade">
            <h2>Prospect intelligence</h2><span className="ccl-time">Thu 10:14</span>
            <span className="ccl-id"><span className="ccl-av"><svg className="sig" viewBox="2 2 96 96" aria-hidden="true"><g className="sig-rot"><path className="sig-ring" d="M88.57 39.402A40 40 0 1 1 60.598 11.43V21.668A29.319 30.387 0 1 0 77.478 39.402Z" /><path className="sig-gap" d="M60.598 11.43A40 40 0 0 1 88.57 39.402H77.478A29.319 30.387 0 0 0 60.598 21.668Z" /><g className="sig-orb"><path className="sig-sq" d="M65.404 16.011h18.585v18.585h-18.585Z" /></g></g></svg></span>Obsession agent for {ws.org}</span>
          </header>
          <section className="ccl-tb ax-fade" style={{ '--d': '.06s' }}>
            <div className="ccl-bar">
              <span className="ccl-src"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.4" aria-hidden="true"><rect x="2.25" y="2.75" width="11.5" height="10.5" rx="1.75" /><path d="M2.25 6.25h11.5M6.25 6.25v7" /></svg><b>Clay</b><i>/</i>UK ecommerce TAM<i>·</i>SMS popup</span>
              <span className="ccl-new"><span className="ax-toggle" />New rows</span>
              <span className="ccl-cnt"><span className="ccl-num"><span>292</span><span>293</span><span>294</span><span>295</span><span>296</span></span>of 300 done</span>
            </div>
            <div className="ccl-r ccl-th"><span>Company</span><span className="ccl-c" style={{ '--ccl-k': '0' }}>Gap</span><span className="ccl-c" style={{ '--ccl-k': '1' }}>Seen</span><span className="ccl-c" style={{ '--ccl-k': '2' }}>What happened</span><span className="ccl-c" style={{ '--ccl-k': '3' }}>Proof</span></div>
            <div className="ccl-r ccl-row ccl-gap" style={{ '--ccl-t': '1.60s' }}><span className="ccl-co"><b>Tidewren Swim</b><small>tidewren.example</small></span><span className="ccl-c ccl-gp" style={{ '--ccl-k': '0' }}><i className="ccl-sk" style={{ width: '88px' }} /><span className="ccl-v">No texts after opt in</span></span><span className="ccl-c ccl-sn" style={{ '--ccl-k': '1' }}><i className="ccl-sk" style={{ width: '32px' }} /><span className="ccl-v">15 Sep</span></span><span className="ccl-c ccl-wh" style={{ '--ccl-k': '2' }}><i className="ccl-sk" style={{ width: '112px', '--ccl-y': '-8px' }} /><i className="ccl-sk" style={{ width: '72px', '--ccl-y': '7px' }} /><span className="ccl-v"><span>Opted in 15 Sep. 3 emails,</span><span>0 texts in 48 h</span></span></span><span className="ccl-c ccl-pf" style={{ '--ccl-k': '3' }}><i className="ccl-sk" /><span className="ccl-v"><span className="ccl-lk"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M6 3.75H4.25a1.5 1.5 0 0 0-1.5 1.5v6.5a1.5 1.5 0 0 0 1.5 1.5h6.5a1.5 1.5 0 0 0 1.5-1.5V10" /><path d="M8.75 2.75h4.5v4.5M13.25 2.75 7.5 8.5" /></svg></span></span></span></div>
            <div className="ccl-r ccl-row" style={{ '--ccl-t': '2.10s' }}><span className="ccl-co"><b>Halvard &amp; Moss</b><small>halvard.example</small></span><span className="ccl-c ccl-gp" style={{ '--ccl-k': '0' }}><i className="ccl-sk" style={{ width: '40px' }} /><span className="ccl-v">No gap</span></span><span className="ccl-c ccl-sn" style={{ '--ccl-k': '1' }}><i className="ccl-sk" style={{ width: '32px' }} /><span className="ccl-v">15 Sep</span></span><span className="ccl-c ccl-wh" style={{ '--ccl-k': '2' }}><i className="ccl-sk" style={{ width: '112px', '--ccl-y': '-8px' }} /><i className="ccl-sk" style={{ width: '72px', '--ccl-y': '7px' }} /><span className="ccl-v"><span>Welcome email in 2 min,</span><span>2 texts, bot answered</span></span></span><span className="ccl-c ccl-pf" style={{ '--ccl-k': '3' }}><i className="ccl-sk" /><span className="ccl-v"><span className="ccl-lk"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M6 3.75H4.25a1.5 1.5 0 0 0-1.5 1.5v6.5a1.5 1.5 0 0 0 1.5 1.5h6.5a1.5 1.5 0 0 0 1.5-1.5V10" /><path d="M8.75 2.75h4.5v4.5M13.25 2.75 7.5 8.5" /></svg></span></span></span></div>
            <div className="ccl-r ccl-row ccl-gap" style={{ '--ccl-t': '2.60s' }}><span className="ccl-co"><b>Fennick Home</b><small>fennick.example</small></span><span className="ccl-c ccl-gp" style={{ '--ccl-k': '0' }}><i className="ccl-sk" style={{ width: '88px' }} /><span className="ccl-v">No welcome email</span></span><span className="ccl-c ccl-sn" style={{ '--ccl-k': '1' }}><i className="ccl-sk" style={{ width: '32px' }} /><span className="ccl-v">15 Sep</span></span><span className="ccl-c ccl-wh" style={{ '--ccl-k': '2' }}><i className="ccl-sk" style={{ width: '112px', '--ccl-y': '-8px' }} /><i className="ccl-sk" style={{ width: '72px', '--ccl-y': '7px' }} /><span className="ccl-v"><span>Signed up 15 Sep. 1 text,</span><span>no emails in 48 h</span></span></span><span className="ccl-c ccl-pf" style={{ '--ccl-k': '3' }}><i className="ccl-sk" /><span className="ccl-v"><span className="ccl-lk"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M6 3.75H4.25a1.5 1.5 0 0 0-1.5 1.5v6.5a1.5 1.5 0 0 0 1.5 1.5h6.5a1.5 1.5 0 0 0 1.5-1.5V10" /><path d="M8.75 2.75h4.5v4.5M13.25 2.75 7.5 8.5" /></svg></span></span></span></div>
            <div className="ccl-r ccl-row ccl-gap" style={{ '--ccl-t': '3.10s' }}><span className="ccl-co"><b>Larkbound</b><small>larkbound.example</small></span><span className="ccl-c ccl-gp" style={{ '--ccl-k': '0' }}><i className="ccl-sk" style={{ width: '88px' }} /><span className="ccl-v">No texts, no bot answer</span></span><span className="ccl-c ccl-sn" style={{ '--ccl-k': '1' }}><i className="ccl-sk" style={{ width: '32px' }} /><span className="ccl-v">15 Sep</span></span><span className="ccl-c ccl-wh" style={{ '--ccl-k': '2' }}><i className="ccl-sk" style={{ width: '112px', '--ccl-y': '-8px' }} /><i className="ccl-sk" style={{ width: '72px', '--ccl-y': '7px' }} /><span className="ccl-v"><span>Opted in 15 Sep. 4 emails,</span><span>0 texts, no bot answer</span></span></span><span className="ccl-c ccl-pf" style={{ '--ccl-k': '3' }}><i className="ccl-sk" /><span className="ccl-v"><span className="ccl-lk"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M6 3.75H4.25a1.5 1.5 0 0 0-1.5 1.5v6.5a1.5 1.5 0 0 0 1.5 1.5h6.5a1.5 1.5 0 0 0 1.5-1.5V10" /><path d="M8.75 2.75h4.5v4.5M13.25 2.75 7.5 8.5" /></svg></span></span></span></div>
          </section>
          <p className="ccl-note ax-fade" style={{ '--d': '.12s' }}><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinejoin="round" aria-hidden="true"><rect x="3.25" y="7" width="9.5" height="6.5" rx="1.5" /><path d="M5.5 7V5.25a2.5 2.5 0 0 1 5 0V7" /></svg>Public sign ups and chat bots only</p>
          <div className="ax-toast ccl-toast"><svg className="sig st-landed" viewBox="2 2 96 96" aria-hidden="true"><g className="sig-rot"><path className="sig-ring" d="M88.57 39.402A40 40 0 1 1 60.598 11.43V21.668A29.319 30.387 0 1 0 77.478 39.402Z" /><path className="sig-gap" d="M60.598 11.43A40 40 0 0 1 88.57 39.402H77.478A29.319 30.387 0 0 0 60.598 21.668Z" /><g className="sig-orb"><path className="sig-sq" d="M65.404 16.011h18.585v18.585h-18.585Z" /></g></g></svg><p><b>Facts back in Clay</b><span>296 rows</span></p><span className="ax-btn">Open</span></div>
        </div>
      </div>
    </div></div></div>
  )
}
